### ISSUE TITLE
I have a little question

### ISSUE THREAD

**Issue by Cute-Newbie** [OPTML-Group/DeepZero#1]
Hello I am very fascinated by the work you have done.
I just want to know exact network architecture, learning rate and other hypermarameters and time it took to train + (what and how many gpu used) to make result of figure 2. 
Thank you for reading

**Comment by Phoveran** [comment]
@damon-demon Please address this question.

**Comment by damon-demon** [comment]
1. Network architecture:  
<img width="1261" alt="Screenshot 2024-03-24 at 7 39 55 AM" src="https://github.com/OPTML-Group/DeepZero/assets/69219031/9922c9cf-00e0-4a76-9aa9-c9a6148607cc">

2. Learning rate: 1e-3 for CGE, and 1e-4 for RGE. (Compared to CGE, the variance of RGE is higher. as the result, normally the learning rate for RGE should be smaller)

3. One NVIDIA RTX A6000 GPU used for training. The training time depends on the number of trainable parameters. (from a few hours to ~2 days)

**Comment by Cute-Newbie** [comment]
Thank you for the comments!
