### ISSUE TITLE
Question on Training Time

### ISSUE THREAD

**Issue by 4ndrelim** [OPTML-Group/DeepZero#2]
Hi, i'm really fascinated by what you've done and was hoping to recreate the reported results. But i seem to be having trouble re-creating them (granted, i've only run the command a few times, some with a few params tweak. But the longest i have run the default command for was an entire day). The accuracy seems to be incrementing slowly, and even after a day, it reaches around 20% and seem to oscillate up and down. 

May i ask, how long did you train the model for? and under what parameter/specification did you use to achieve the high results mentioned in the paper?

**Comment by Phoveran** [comment]
Hi, thank you for this question.
My I know what platform you are using (*e.g.,* GPUs)? We used 4xA6000 GPUs to run the experiment. 
Oscillating is not observed in our experiment. Could you share your log with us?

**Comment by 4ndrelim** [comment]
Hi, sure, below is a screenshot. Im running on only 2x A4000 GPUs but was hoping if the same number of epochs is hit, the accuracy could be replicated (or marginally smaller). I ran the default command.
<img width="966" alt="Screenshot 2024-03-26 at 9 37 24 PM" src="https://github.com/OPTML-Group/DeepZero/assets/95348273/03ed5c39-be78-4eb8-b684-025a34570842">
